# 服务器基本配置
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 连接mysql
  datasource:
    url: jdbc:mysql://43.143.151.29:3306/TroForum?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: 1482501212@qq
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB

# sa-token框架
sa-token:
  token-name: satoken
  # token有效时间
  timeout: 2592000
  # token临时有效时间
  activity-timeout: -1
  # 允许多端同时登录
  is-concurrent: true
  # 共用一个token
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false